### ISSUE TITLE
Fix bugs found by fuzzing

### ISSUE THREAD

**Issue by flyx** [yaml/AdaYaml#7]
This list of bugs has been discovered by Lionel with fuzzing tests.

**Note**: In the reports, there were also crashes with a `ADA.STRINGS.UTF_ENCODING.ENCODING_ERROR`. I intend to keep those as they are, because an encoding error is more low-level than a lexer error and should be distinguished.

 * [x] #3 (Constraint_Error when loading duplicate keys to DOM)
 * [x] #4 (Hex sequence parsing does not check for overflow)
 * [x] #5 (Long scalar can lead to Constraint_Error in Text package)
 * [x] #6 (YAML input with deep nesting may raise Storage_Error due to recursive DOM loading)
 * [x] #8 (Adding a key-value pair where the key is a mapping to a DOM node is sometimes very slow)
